# Build stage
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./client ./
RUN npm install && npm run build

# Serve stage
FROM node:24-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
